apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /home/panda/fondadata
  claimRef:
    namespace: hoegvinc
    name: myclaim

