apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleep-pod
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["sleep", "3600"] # Sleep for an hour, you can adjust the time
    volumeMounts:
    - mountPath: /data # Mount path in the container
      name: data-volume
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: myclaim # Use the name of your PVC here
